{
 "title": "HCIBench Vdbench Monitoring",
 "tags": [ "vdbench" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Testname", "query": "vdbench.*" },
   { "name": "Testcase", "query": "vdbench.$Testname.*" }
  ]
 },
 "panels": [
  { "title": "Vdbench Single Stats (Current)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aggregate(vdbench.$Testname.$Testcase.*.localhost.i_o_rate, 'sum')"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "aggregate(scale(scale(vdbench.$Testname.$Testcase.*.localhost.MB_sec_1024**2, 1024), 1024), 'sum')"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(vdbench.$Testname.$Testcase.*.localhost.resp_time)"
    }
   ]
  },
  {
   "title": "Std Dev Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(vdbench.$Testname.$Testcase.*.localhost.resp_stddev)"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(vdbench.$Testname.$Testcase.*.localhost.read_resp)"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(vdbench.$Testname.$Testcase.*.localhost.write_resp)"
    }
   ]
  },
  {
   "title": "Block Size (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "avg(vdbench.$Testname.$Testcase.*.localhost.bytes_i_o)"
    }
   ]
  },
  {
   "title": "Number of Vdbench VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "countSeries(vdbench.$Testname.$Testcase.*.localhost.bytes_i_o, vdbench.*)"
    }
   ]
  },
  {
   "title": "Total Outstanding I/Os",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aggregate(vdbench.$Testname.$Testcase.*.localhost.queue_depth, 'sum')"
    }
   ]
  },
  {
   "title": "Read Ratio",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "target": "avg(vdbench.$Testname.$Testcase.*.localhost.read_pct)"
    }
   ]
  },
  {
   "title": "Read 95th Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "nPercentile(avg(vdbench.$Testname.$Testcase.*.localhost.read_resp), 95)"
    }
   ]
  },
  {
   "title": "Write 95th Percentile Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "nPercentile(avg(vdbench.$Testname.$Testcase.*.localhost.write_resp), 95)"
    }
   ]
  },
  { "title": "Vdbench Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Vdbench IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vdbench.$Testname.$Testcase.*.localhost.i_o_rate, 3)"
    }
   ]
  },
  {
   "title": "Vdbench Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vdbench.$Testname.$Testcase.*.localhost.MB_sec_1024**2, 3)"
    }
   ]
  },
  {
   "title": "Vdbench Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vdbench.$Testname.$Testcase.*.localhost.read_resp, 3)"
    }
   ]
  },
  {
   "title": "Vdbench Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vdbench.$Testname.$Testcase.*.localhost.write_resp, 3)"
    }
   ]
  },
  {
   "title": "Read 95th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nPercentile(vdbench.$Testname.$Testcase.*.localhost.read_resp, 95), 3)"
    }
   ]
  },
  {
   "title": "Write 95th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nPercentile(vdbench.$Testname.$Testcase.*.localhost.write_resp, 95), 3)"
    }
   ]
  },
  {
   "title": "Vdbench Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vdbench.$Testname.$Testcase.*.localhost.queue_depth, 3)"
    }
   ]
  },
  {
   "title": "Vdbench Latency Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vdbench.$Testname.$Testcase.*.localhost.resp_stddev, 3)"
    }
   ]
  }
 ]
}